language: generic 
sudo: required
services:
  - docker
before_install:
  - docker build -t nishanprime/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true nishanprime/react-test npm test -- --coverage

after_success:
  - docker build -t nishanprime/multi-client ./client
  - docker build -t nishanprime/multi-nginx ./nginx
  - docker build -t nishanprime/multi-server ./server
  - docker build -t nishanprime/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push nishanprime/multi-client
  - docker push nishanprime/multi-nginx
  - docker push nishanprime/multi-server
  - docker push nishanprime/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "multi-docker"
  env: "Multidocker-env"
  bucket_name: "elasticbeanstalk-us-east-2-410333440162"
  bucket_path: "docker-multi"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
